# Generated by Django 4.1.2 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0006_uiux'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('EmployeeID', models.IntegerField()),
                ('HoursPerWeek', models.IntegerField()),
                ('MonthlySalary', models.IntegerField()),
            ],
        ),
    ]
