# Generated by Django 4.1.2 on 2022-10-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0007_salesmarketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemanalyst',
            name='MonthlySalary',
        ),
        migrations.AlterField(
            model_name='backend',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backend',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backend',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datascientist',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datascientist',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datascientist',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesmarketing',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesmarketing',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesmarketing',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='softwaretester',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='softwaretester',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='softwaretester',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemanalyst',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemanalyst',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uiux',
            name='EmployeeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uiux',
            name='HoursPerWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uiux',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
    ]
