# Generated by Django 4.1.2 on 2022-10-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0008_remove_systemanalyst_monthlysalary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemanalyst',
            name='MonthlySalary',
            field=models.IntegerField(default=0),
        ),
    ]
