# Generated by Django 4.1.2 on 2022-10-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0010_remove_systemanalyst_monthlysalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='datascientist',
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='salesmarketing',
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='softwaretester',
            name='MonthlySalary',
        ),
        migrations.RemoveField(
            model_name='uiux',
            name='MonthlySalary',
        ),
    ]
