# Generated by Django 4.1.2 on 2022-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0011_remove_backend_monthlysalary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemanalyst',
            name='HoursPerWeek',
        ),
        migrations.AddField(
            model_name='systemanalyst',
            name='EmployeeType',
            field=models.CharField(choices=[('40', 'Full Time'), ('20', 'Part Time'), ('44', 'Team Lead')], default='FULL', max_length=9),
        ),
    ]
