# Generated by Django 4.1.2 on 2022-10-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0013_rename_employeetype_systemanalyst_hoursperweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemanalyst',
            name='HoursPerWeek',
        ),
        migrations.AddField(
            model_name='systemanalyst',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PART TIME'), (2, 'FULL TIME'), (3, 'TEAM LEAD')], default=2),
        ),
    ]
