# Generated by Django 4.1.2 on 2022-10-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0014_remove_systemanalyst_hoursperweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwaretester',
            name='HoursPerWeek',
        ),
        migrations.AddField(
            model_name='softwaretester',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
        migrations.AlterField(
            model_name='systemanalyst',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
    ]
