# Generated by Django 4.1.2 on 2022-10-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0015_remove_softwaretester_hoursperweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='HoursPerWeek',
        ),
        migrations.RemoveField(
            model_name='datascientist',
            name='HoursPerWeek',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='HoursPerWeek',
        ),
        migrations.RemoveField(
            model_name='salesmarketing',
            name='HoursPerWeek',
        ),
        migrations.RemoveField(
            model_name='uiux',
            name='HoursPerWeek',
        ),
        migrations.AddField(
            model_name='backend',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
        migrations.AddField(
            model_name='datascientist',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
        migrations.AddField(
            model_name='frontend',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
        migrations.AddField(
            model_name='salesmarketing',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
        migrations.AddField(
            model_name='uiux',
            name='hoursworking',
            field=models.PositiveSmallIntegerField(choices=[(20, 'PART TIME'), (40, 'FULL TIME'), (44, 'TEAM LEAD')], default=40),
        ),
    ]
